[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib @ ^6.0.0
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    adafruit/Adafruit MLX90614 Library @ ^2.1.3
    adafruit/Adafruit ADXL345 @ ^1.3.2
